spring:
  datasource:
    url: jdbc:h2:mem:sback2024
    username: sback2024
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true  # Correção aqui (de 'enable' para 'enabled')
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
